
services:
  client-server:
    image: tomoadmin/idv-client-server:test-0.0.2.8
    build:
      context: ../
      dockerfile: typescript/Dockerfile
      target: development
      additional_contexts:
          tomo-idv-client-node: ../../tomo-idv-client-node

  client-server-test:
    image: tomoadmin/idv-client-server:test-0.0.2.8

    ports:
      - "8080:3000"

    env_file:
      - ../.env.idv-client-server
      - ../.env.domain.test


  client-server-dev:
    image: tomoadmin/idv-client-server:test-0.0.2.8

    ports:
      - "8081:3000"

    env_file:
      - ../.env.idv-client-server
      - ../.env.domain.dev


  client-server-prod:
    image: tomoadmin/idv-client-server:test-0.0.2.8

    ports:
      - "80:3000"

    env_file:
      - ../.env.idv-client-server
      - ../.env.domain.prod
