
services:
  client-server:
    image: tomoadmin/idv-client-server:1.2.1
    build:
      context: ../
      dockerfile: typescript/Dockerfile
      target: development

  client-server-test:
    image: tomoadmin/idv-client-server:1.2.1

    ports:
      - "8080:3000"

    env_file:
      - ../.env.idv-client-server
      - ../.env.domain.test


  client-server-dev:
    image: tomoadmin/idv-client-server:1.2.1

    ports:
      - "8081:3000"

    env_file:
      - ../.env.idv-client-server
      - ../.env.domain.dev


  client-server-prod:
    image: tomoadmin/idv-client-server:1.2.1

    ports:
      - "80:3000"

    env_file:
      - ../.env.idv-client-server
      - ../.env.domain.prod
