services:
  typescript:
    build:
      context: .
      dockerfile: typescript/Dockerfile
      target: development
      additional_contexts:
        tomo-idv-client-node: ../tomo-idv-client-node
    ports:
      - "4300:3000"
    env_file:
      - typescript/.env

  kotlin:
    build:
      context: .
      dockerfile: kotlin/Dockerfile
      additional_contexts:
        tomo-idv-client-kotlin: ../tomo-idv-client-kotlin
    ports:
      - "4301:3000"
    env_file:
      - kotlin/.env
