
services:
  bff-kotlin:
    image: tomoadmin/idv-bff-kotlin:dev
    build:
      context: ../
      dockerfile: kotlin/Dockerfile

    ports:
      - "3000:3000"

    env_file:
      - ../.env.idv-client-server
      - ../.env.domain.test
      

  bff-kotlin-dev:
    image: tomoadmin/idv-bff-kotlin:dev
    build:
      context: ../
      dockerfile: kotlin/Dockerfile

    ports:
      - "3001:3000"

    env_file:
      - ../.env.idv-client-server
      - ../.env.domain.dev
